#:import FadeTransition kivy.uix.screenmanager.FadeTransition

<WindowManager>:
    MainWindow:

<MainWindow>:
    name: 'MainWindow'

    FloatLayout:
        canvas.before:
            Rectangle:
                source: 'Images/backgrounds/main_background.png'
                size: self.size
                pos: self.pos

        Image:
            source: 'Images/logo/main_logo.png'
            size_hint: (1, None)
            height: self.width * self.texture_size[1] / self.texture_size[0]
            pos_hint: {'center_x': 0.5, 'top': 1}

        BoxLayout:
            orientation: 'vertical'
            size_hint: (0.6, None)
            height: self.minimum_height
            spacing: dp(15)
            pos_hint: {'center_x': 0.5, 'y': 0.1}
            Button:
                id: new_game_button
                text: 'Новая игра'
                size_hint_y: None
                height: dp(60)
                background_normal: 'Images/buttons/newGame/button_normal.png'
                background_down: 'Images/buttons/newGame/button_press.png'
                on_release: root.change_button_image(self)
            Button:
                id: continue_button
                text: 'Продолжить'
                size_hint_y: None
                height: dp(60)
                background_normal: 'Images/buttons/continue/button_normal.png'
                background_down: 'Images/buttons/continue/button_press.png'
                on_release: root.change_button_image(self)
            Button:
                id: settings_button
                text: 'Настройки'
                size_hint_y: None
                height: dp(60)
                background_normal: 'Images/buttons/settings/button_normal.png'
                background_down: 'Images/buttons/settings/button_press.png'
                on_release: root.change_button_image(self)
            Button:
                id: exit_button
                text: 'Выход'
                size_hint_y: None
                height: dp(60)
                background_normal: 'Images/buttons/exit/button_normal.png'
                background_down: 'Images/buttons/exit/button_press.png'
                on_release: app.stop()